---
- name: "create {{ instructor.group }} group"
  group: "name={{ instructor.group }}"

- name: "add {{ instructor.user }} user"
  user: name={{ instructor.user }}
        group={{ instructor.group }}
        shell={{ instructor.shell }}
        password={{ instructor.password }}

- name: "Add {{ instructor.user }} to sudoers"
  action: lineinfile 
          dest=/etc/sudoers 
          regexp="{{ instructor.user }} ALL" 
          line="{{ instructor.user }} ALL=(ALL) ALL" 
          state=present
    
- name: "add public key to {{ instructor.user }} authorized keys"
  authorized_key: "user={{ instructor.user }} key='{{ item }}'"
  with_file: instructor.public_key_files

- name: "allow {{ instructor.user }} to ssh"
  lineinfile: dest=/etc/ssh/sshd_config 
              regexp="AllowUsers {{ instructor.user }}"
              line="AllowUsers {{ instructor.user }}"

- name: restart ssh
  service: name=ssh 
           state=restarted
